from . import survey_survey
from . import slide_channel
from . import res_users
from . import mail_message
from . import product_template
from . import repair_order
from . import assignment_parts
from . import fleet_vehicle
from . import res_partner
from . import helpdesk_ticket
from . import project_project